// packages/angular/src/lib/ebin-player.component.ts
import { Component, ElementRef, EventEmitter, Input, NgZone, OnDestroy, OnInit, Output } from '@angular/core';
import { createPlayer, type PlayerOptions, type ControlBarConfig, type PlayerTheme, type PluginDefinition, version as coreVersion } from '@ebin-player/core';
import { ensureStylesInjected, type StyleInjectionMode } from './style-injection';

@Component({
  selector: 'ebin-player',
  template: '<div class="ebin-player-container"></div>',
  standalone: false,
})
export class EbinPlayerComponent implements OnInit, OnDestroy {
  @Input() src!: PlayerOptions['src'];
  @Input() autoplay?: PlayerOptions['autoplay'];
  @Input() muted?: PlayerOptions['muted'];
  @Input() volume?: PlayerOptions['volume'];
  @Input() playbackRate?: PlayerOptions['playbackRate'];
  @Input() poster?: PlayerOptions['poster'];
  @Input() width?: PlayerOptions['width'];
  @Input() height?: PlayerOptions['height'];
  @Input() loop?: PlayerOptions['loop'];
  @Input() preload?: PlayerOptions['preload'];
  @Input() crossOrigin?: PlayerOptions['crossOrigin'];
  @Input() playsInline?: PlayerOptions['playsInline'];
  @Input() uiMode?: PlayerOptions['uiMode'];
  @Input() uiConfig?: ControlBarConfig;
  @Input() theme?: PlayerTheme;
  @Input() builtinPlugins?: PlayerOptions['builtinPlugins'];
  @Input() debug?: PlayerOptions['debug'];
  @Input() logger?: PlayerOptions['logger'];
  @Input() plugins?: Array<PluginDefinition | (() => PluginDefinition)>;
  @Input() styleInjection: StyleInjectionMode = 'auto';
  @Input() stylesheetUrl?: string;
  @Input() nonce?: string;
  @Input() injectOnceKey?: string;

  @Output() ready = new EventEmitter<void>();
  @Output() play = new EventEmitter<void>();
  @Output() pause = new EventEmitter<void>();
  @Output() timeupdate = new EventEmitter<number>();
  @Output() ended = new EventEmitter<void>();
  @Output() error = new EventEmitter<unknown>();
  @Output() loadedmetadata = new EventEmitter<void>();
  @Output() seeking = new EventEmitter<void>();
  @Output() seeked = new EventEmitter<void>();
  @Output() volumechange = new EventEmitter<{ volume: number; muted: boolean }>();
  @Output() ratechange = new EventEmitter<number>();
  @Output() fullscreenchange = new EventEmitter<boolean>();

  private player: any | null = null;

  constructor(private host: ElementRef<HTMLElement>, private zone: NgZone) {}

  ngOnInit(): void {
    this.zone.runOutsideAngular(() => this.initializePlayer());
  }

  ngOnDestroy(): void {
    this.destroyPlayer();
  }

  private initializePlayer(): void {
    const container = this.host.nativeElement.querySelector('.ebin-player-container') as HTMLElement | null;
    if (!container) return;

    if (typeof window !== 'undefined' && typeof document !== 'undefined') {
      ensureStylesInjected({
        mode: this.styleInjection,
        stylesheetUrl: this.stylesheetUrl,
        nonce: this.nonce,
        injectOnceKey: this.injectOnceKey,
        packageVersion: coreVersion,
      });
    }

    try {
      const options: PlayerOptions = {
        src: this.src,
        autoplay: this.autoplay,
        muted: this.muted,
        volume: this.volume,
        playbackRate: this.playbackRate,
        poster: this.poster,
        width: this.width,
        height: this.height,
        loop: this.loop,
        preload: this.preload,
        crossOrigin: this.crossOrigin,
        playsInline: this.playsInline,
        uiMode: this.uiMode,
        uiConfig: this.uiConfig,
        theme: this.theme,
        builtinPlugins: this.builtinPlugins,
        debug: this.debug,
        logger: this.logger,
      } as PlayerOptions;

      const instance = createPlayer(container, options);
      this.player = instance;

      if (Array.isArray(this.plugins) && this.plugins.length > 0) {
        this.plugins.forEach((p) => {
          try {
            const def = typeof p === 'function' ? p() : p;
            if (def) instance.use(def as any);
          } catch (e) {
            this.zone.run(() => this.error.emit(e));
          }
        });
      }

      instance.on('play', () => this.zone.run(() => this.play.emit()));
      instance.on('pause', () => this.zone.run(() => this.pause.emit()));
      instance.on('timeupdate', () => this.zone.run(() => this.timeupdate.emit(instance.getCurrentTime())));
      instance.on('ended', () => this.zone.run(() => this.ended.emit()));
      instance.on('error', (e: any) => this.zone.run(() => this.error.emit(e)));
      instance.on('loadedmetadata', () => this.zone.run(() => this.loadedmetadata.emit()));
      instance.on('seeking', () => this.zone.run(() => this.seeking.emit()));
      instance.on('seeked', () => this.zone.run(() => this.seeked.emit()));
      instance.on('volumechange', () => this.zone.run(() => this.volumechange.emit({ volume: instance.getVolume(), muted: instance.getMuted() })));
      instance.on('ratechange', () => this.zone.run(() => this.ratechange.emit(instance.getPlaybackRate())));
      instance.on('fullscreenchange', () => this.zone.run(() => this.fullscreenchange.emit(instance.isFullscreen())));

      this.zone.run(() => this.ready.emit());
    } catch (e) {
      this.zone.run(() => this.error.emit(e));
    }
  }

  getInstance(): any | null {
    return this.player;
  }

  private destroyPlayer(): void {
    if (this.player) {
      try {
        this.player.destroy?.();
      } catch {}
      this.player = null;
    }
  }
}

// packages/vue2/src/EbinPlayer.vue
<template>
  <div
    ref="container"
    :class="containerClassName"
    :style="containerStyle"
    v-bind="containerProps"
  />
</template>

<script lang="ts">
import Vue from 'vue';
import {
  createPlayer,
  type PlayerOptions,
  type ControlBarConfig,
  type PlayerTheme,
  type PluginDefinition,
  version as coreVersion,
} from '@ebin-player/core';
import { ensureStylesInjected, type StyleInjectionMode } from './styleInjection';

export interface VueEbinPlayerProps {
  // Core options (direct pass-through)
  src: PlayerOptions['src'];
  autoplay?: PlayerOptions['autoplay'];
  muted?: PlayerOptions['muted'];
  volume?: PlayerOptions['volume'];
  playbackRate?: PlayerOptions['playbackRate'];
  poster?: PlayerOptions['poster'];
  width?: PlayerOptions['width'];
  height?: PlayerOptions['height'];
  loop?: PlayerOptions['loop'];
  preload?: PlayerOptions['preload'];
  crossOrigin?: PlayerOptions['crossOrigin'];
  playsInline?: PlayerOptions['playsInline'];

  // UI & Theme
  uiMode?: PlayerOptions['uiMode'];
  uiConfig?: ControlBarConfig;
  theme?: PlayerTheme;

  // Builtin plugins
  builtinPlugins?: PlayerOptions['builtinPlugins'];

  // Debug
  debug?: PlayerOptions['debug'];
  logger?: PlayerOptions['logger'];

  // External plugins
  plugins?: Array<PluginDefinition | (() => PluginDefinition)>;

  // Vue specifics
  containerStyle?: Record<string, any>;
  containerClassName?: string;
  containerProps?: Record<string, any>;
  reinitializeOn?: Array<'src' | 'uiMode'>;
  ssr?: boolean;

  // Style injection
  styleInjection?: StyleInjectionMode;
  stylesheetUrl?: string;
  nonce?: string;
  injectOnceKey?: string;
}

export interface VueEbinPlayerRef {
  getInstance: () => any;
}

function pickOptions(props: VueEbinPlayerProps): PlayerOptions {
  const {
    src,
    autoplay,
    muted,
    volume,
    playbackRate,
    poster,
    width,
    height,
    loop,
    preload,
    crossOrigin,
    playsInline,
    uiMode,
    uiConfig,
    theme,
    builtinPlugins,
    debug,
    logger,
  } = props;
  return {
    src,
    autoplay,
    muted,
    volume,
    playbackRate,
    poster,
    width,
    height,
    loop,
    preload,
    crossOrigin,
    playsInline,
    uiMode,
    uiConfig,
    theme,
    builtinPlugins,
    debug,
    logger,
  } as PlayerOptions;
}

export default Vue.extend({
  name: 'EbinPlayer',
  props: {
    // Core options
    src: {
      type: [String, Object] as Vue.PropType<PlayerOptions['src']>,
      required: true,
    },
    autoplay: Boolean,
    muted: Boolean,
    volume: Number,
    playbackRate: Number,
    poster: String,
    width: [Number, String] as Vue.PropType<PlayerOptions['width']>,
    height: [Number, String] as Vue.PropType<PlayerOptions['height']>,
    loop: Boolean,
    preload: String as Vue.PropType<PlayerOptions['preload']>,
    crossOrigin: String as Vue.PropType<PlayerOptions['crossOrigin']>,
    playsInline: Boolean,

    // UI & Theme
    uiMode: String as Vue.PropType<PlayerOptions['uiMode']>,
    uiConfig: Object as Vue.PropType<ControlBarConfig>,
    theme: Object as Vue.PropType<PlayerTheme>,

    // Builtin plugins
    builtinPlugins: Object as Vue.PropType<PlayerOptions['builtinPlugins']>,

    // Debug
    debug: Boolean,
    logger: Object as Vue.PropType<PlayerOptions['logger']>,

    // External plugins
    plugins: Array as Vue.PropType<Array<PluginDefinition | (() => PluginDefinition)>>,

    // Vue specifics
    containerStyle: Object as Vue.PropType<Record<string, any>>,
    containerClassName: String,
    containerProps: Object as Vue.PropType<Record<string, any>>,
    reinitializeOn: {
      type: Array as Vue.PropType<Array<'src' | 'uiMode'>>,
      default: () => ['src', 'uiMode'],
    },
    ssr: {
      type: Boolean,
      default: true,
    },

    // Style injection
    styleInjection: {
      type: String as Vue.PropType<StyleInjectionMode>,
      default: 'auto',
    },
    stylesheetUrl: String,
    nonce: String,
    injectOnceKey: String,
  },
  data() {
    return {
      player: null as any,
      isInitialized: false,
    };
  },
  computed: {
    options(): PlayerOptions {
      return pickOptions(this.$props as VueEbinPlayerProps);
    },
    containerStyle(): Record<string, any> {
      return {
        width: this.width as any,
        height: this.height as any,
        ...this.containerStyle,
      };
    },
  },
  watch: {
    options: {
      handler(newOptions: PlayerOptions) {
        if (this.isInitialized && this.player) {
          // Handle incremental updates
          if (newOptions.muted !== undefined) {
            try {
              this.player.setMuted(!!newOptions.muted);
            } catch {}
          }
          if (newOptions.volume !== undefined) {
            try {
              this.player.setVolume(newOptions.volume);
            } catch {}
          }
          if (newOptions.playbackRate !== undefined) {
            try {
              this.player.setPlaybackRate(newOptions.playbackRate);
            } catch {}
          }
        }
      },
      deep: true,
    },
    'options.uiConfig': {
      handler(newConfig: ControlBarConfig) {
        if (this.isInitialized && this.player && newConfig) {
          try {
            this.player.updateUIConfig(newConfig);
          } catch {}
        }
      },
      deep: true,
    },
    'options.theme': {
      handler(newTheme: PlayerTheme) {
        if (this.isInitialized && this.player && newTheme) {
          try {
            this.player.updateUITheme(newTheme);
          } catch {}
        }
      },
      deep: true,
    },
  },
  mounted() {
    this.initializePlayer();
  },
  beforeDestroy() {
    this.destroyPlayer();
  },
  methods: {
    initializePlayer() {
      if (this.ssr && typeof window === 'undefined') return;
      
      const container = this.$refs.container as HTMLElement;
      if (!container) return;

      // Style injection (client only)
      if (typeof window !== 'undefined' && typeof document !== 'undefined') {
        ensureStylesInjected({
          mode: this.styleInjection,
          stylesheetUrl: this.stylesheetUrl,
          nonce: this.nonce,
          injectOnceKey: this.injectOnceKey,
          packageVersion: coreVersion,
        });
      }

      try {
        const instance = createPlayer(container, this.options);
        this.player = instance;

        // External plugins
        if (Array.isArray(this.plugins) && this.plugins.length > 0) {
          this.plugins.forEach((p) => {
            try {
              const def = typeof p === 'function' ? p() : p;
              if (def) instance.use(def as any);
            } catch (e) {
              this.$emit('error', e);
            }
          });
        }

        // Bind events
        this.bindEvents();

        this.isInitialized = true;
        this.$emit('ready');
      } catch (e) {
        this.$emit('error', e);
      }
    },

    bindEvents() {
      if (!this.player) return;

      const events = [
        'play', 'pause', 'ended', 'error', 'loadedmetadata',
        'seeking', 'seeked', 'timeupdate', 'volumechange',
        'ratechange', 'fullscreenchange', 'enterpictureinpicture',
        'leavepictureinpicture'
      ];

      events.forEach(event => {
        this.player.on(event, (eventData: any) => {
          this.$emit(event, eventData);
        });
      });
    },

    destroyPlayer() {
      if (this.player) {
        try {
          this.player.destroy();
        } catch {}
        this.player = null;
        this.isInitialized = false;
      }
    },

    // Public methods
    getInstance() {
      return this.player;
    },
  },
});
</script>
